receivers:
  filelog:
    include: [ /var/log/access-structured.log ]
    start_at: beginning
    operators:
      - type: json_parser
        timestamp:
          parse_from: attributes.time_local
          layout: '%Y-%m-%d %H:%M:%S'
processors:
  batch:
    timeout: 5s
    send_batch_size: 10000
exporters:
  debug:
    verbosity: basic
  clickhouse:
    endpoint: https://cr4w19rzls.us-east-2.aws.clickhouse.cloud:8443?compress=lz4&async_insert=1&username=default&password=ijn.fS3w.eDul
    logs_table_name: access_logs
    create_schema: true
    timeout: 10s
    database: default
    sending_queue:
      queue_size: 5
      enabled: false
    retry_on_failure:
      enabled: true
      initial_interval: 10s
      max_interval: 30s
      max_elapsed_time: 300s
service:
  pipelines:
    logs:
      receivers: [filelog]
      processors: [batch]
      exporters: [debug,clickhouse]
